# 端口号
server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  # 优雅停机
  shutdown: graceful
# 应用名称
spring:
  # 优雅停机等待时间
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: SpringBootDemo
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  profiles:
    active: company
# 默认配置文件
application:
  hello: hello,springboot
# logback配置文件
logging:
  config: classpath:logback-spring.xml
  level:
    RocketmqRemoting: ERROR
# mybatis
mybatis:
  mapper-locations: classpath:mappers/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

system:
  max-session: 100